# coding: utf-8

"""
    MessageMedia REST API

    Australia’s Leading Messaging Solutions for Business and Enterprise.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

# import models into sdk package
from .models.delivery_report import DeliveryReport
from .models.delivery_report_id import DeliveryReportId
from .models.delivery_reports import DeliveryReports
from .models.error import Error
from .models.error_details import ErrorDetails
from .models.message import Message
from .models.message_list import MessageList
from .models.message_metadata import MessageMetadata
from .models.messages import Messages
from .models.new_message import NewMessage
from .models.replies import Replies
from .models.reply import Reply
from .models.reply_id import ReplyId
from .models.status import Status

# import apis into sdk package
from .apis.delivery_reports_api import DeliveryReportsApi
from .apis.messaging_api import MessagingApi
from .apis.replies_api import RepliesApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
